someblog/blog/models/__init__.py
from .models import *

someblog/blog/models/models.py
import re
from datetime import datetime

from someblog.blog import db


def slugify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', s)


post_tags = db.Table('post_tags',
                     db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
                     db.Column('tag_id', db.Integer, db.ForeignKey('tag.id')))


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())

    tags = db.relationship('Tag', secondary=post_tags, backref=db.backref('posts', lazy='dynamic'))

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.generate_slug()

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)

    def __repr__(self):
        return f'<Post id: {self.id}, title: {self.title}>'


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    slug = db.Column(db.String(255))

    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.slug = slugify(self.name)

    def __repr__(self):
        return f'<Tag id: {self.id}, name: {self.name}>'

someblog/blueprints/blog/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    body = TextAreaField('Body', validators=[DataRequired()])
    submit = SubmitField("Create Post")

someblog/blog/__init__.py
import os

from flask import Flask
from flask_bootstrap import Bootstrap
from flask_migrate import Migrate, MigrateCommand
from flask_navigation import Navigation
from flask_script import Manager
from flask_sqlalchemy import SQLAlchemy

from someblog.blog.config import TestBuild

app = Flask(__name__)
app.secret_key = os.urandom(16)
app.config.from_object(TestBuild)

Bootstrap(app)
db = SQLAlchemy(app)
migrate = Migrate(app, db)
manager = Manager(app)

manager.add_command('db', MigrateCommand)

nav = Navigation(app)
from .navbar import nav

someblog/blog/config/__init__.py
from .config import *

someblog/blog/view/__init__.py
from .view import *

someblog/blueprints/blog/__init__.py
import requests
from flask import Blueprint, render_template, \
    redirect, url_for, flash, request

from someblog.blog import db
from someblog.blog.models import Post, Tag
from someblog.blueprints.blog.forms import PostForm

cat_fact = requests.get('https://cat-fact.herokuapp.com/facts/random').json()['text']
blog = Blueprint('blog', __name__, template_folder='templates', url_prefix='/api')


@blog.route('/create', methods=['POST', 'GET'])
def create_post():
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']

        try:
            post = Post(title=title, body=body)
            db.session.add(post)
            db.session.commit()
        except:
            print("Wrong")

        return redirect(url_for('blog.index'))

    form = PostForm()
    return render_template('blog/create_post.html', form=form)


@blog.route('/')
def index():
    search = request.args.get('search')
    if search:
        posts = Post.query.filter(Post.title.contains(search) | Post.body.contains(search))
        try:
            posts[0]
        except IndexError:
            flash(u'<b>404 Not Found</b> The requested posts were not found. If you entered the '
                  u'URL manually please check your spelling and try again.', 'danger')
            return redirect(url_for('blog.index'))
    else:
        posts = Post.query.order_by(Post.created.desc())

    return render_template('blog/index.html', posts=posts, cat_fact=cat_fact)


@blog.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug == slug).first()
    if post:
        tags = post.tags
        return render_template('blog/post.html', post=post, tags=tags)
    else:
        flash(u'<b>404 Not Found</b> The requested post was not found. If you entered the '
              u'URL manually please check your spelling and try again.', 'danger')
        return redirect(url_for('blog.index'))


@blog.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first()
    if tag:
        posts = tag.posts.all()
        return render_template('blog/tag.html', posts=posts, tag=tag)
    else:
        flash(u'<b>404 Not Found</b> The requested tag was not found. If you entered the '
              u'URL manually please check your spelling and try again.', 'danger')
        return redirect(url_for('blog.index'))

someblog/main.py
from someblog.blog import app
from someblog.blog import db

from someblog.blueprints.blog import blog
import someblog.blog.view

app.register_blueprint(blog, url_prefix='/blog')

if __name__ == '__main__':
    app.run()

someblog/blog/templates/base/flash.html
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <ul class="alert alert-{{ category }}" role="alert">
                <li>{{ message | safe }}</li>
            </ul>
        {% endfor %}
    {% endif %}
{% endwith %}

someblog/blog/templates/base/nav.html
<nav name="AthonD" class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button"
            data-toggle="collapse"
            data-target="#navbarTogglerDemo03"
            aria-controls="navbarTogglerDemo03"
            aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{{ url_for('index') }}">Navbar</a>

    <div class="collapse navbar-collapse"
         id="navbarTogglerDemo03">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            {% for item in nav.top %}
                <li class="nav-item {{ 'active' if item.is_active else '' }}">
                    <a class="nav-link"
                       href="{{ item.url }}">{{ item.label }}</a>
                </li>
            {% endfor %}
        </ul>
        <form class="form-inline my-2 my-lg-0" method="GET">
            <input name="search" class="form-control mr-sm-2" type="search"
                   placeholder="Search" aria-label="Search" value="{{ request.args.get('search', '') }}"
            />
            <button class="btn btn-outline-light my-2 my-sm-0"
                    type="submit">Search
            </button>
        </form>
    </div>
</nav>

someblog/blog/templates/base/nav.html.j2
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button"
            data-toggle="collapse"
            data-target="#navbarTogglerDemo03"
            aria-controls="navbarTogglerDemo03"
            aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{{ url_for('index') }}">Navbar</a>

    <div class="collapse navbar-collapse"
         id="navbarTogglerDemo03">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            {% for item in nav.top %}
                <li class="nav-item {{ 'active' if item.is_active else '' }}">
                    <a class="nav-link"
                       href="{{ item.url }}">{{ item.label }}</a>
                </li>
            {% endfor %}
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search"
                   placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0"
                    type="submit">Search
            </button>
        </form>
    </div>
</nav>

someblog/blog/templates/blog.html.j2
{% extends "bootstrap/base.html" %}

{% block navbar %}
    {% include 'base/nav.html.j2' %}
{% endblock %}

{% block title %}
    Blog
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <h1>Hello, bloger</h1>
        </div>
    </div>
{% endblock %}

someblog/blog/templates/index.html
{% extends "bootstrap/base.html" %}

{% block navbar %}
    {% include 'base/nav.html' %}
{% endblock %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <h1>Welcome to my website</h1>
        </div>
    </div>
{% endblock %}

someblog/blueprints/blog/templates/blog/create_post.html
{% extends "bootstrap/base.html" %}
{% include "base/nav.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="container col-md-6">
        {{ wtf.quick_form(form) }}
    </div>
{% endblock %}

someblog/blueprints/blog/templates/blog/index.html
{% extends "bootstrap/base.html" %}

{% block navbar %}
    {% include 'base/nav.html' %}
{% endblock navbar %}

{% block title %}
    Posts
{% endblock title %}

{% block content %}
    {% block main %}

        {% include 'base/flash.html' %}

        <div class="container">

            <h1 class="">Posts</h1>
            <br>
            <div class="list-group list-group-flush">
                <div class="list-group-item-secondary text-md-center mx-5">
                    <p class="m-2">
                        {{ cat_fact }}
                    </p>
                </div>
                <br>
                {% for post in posts[:5] %}
                    <a class="list-group-item list-group-item-action" href="{{ post.slug }}">
                        <figure>
                            <span class="h3 ml-4">{{ post.title }}</span>
                            <figcaption class="blockquote-footer">
                                {% if post.body == post.body[:90] %}
                                    {{ post.body }}
                                {% else %}
                                    {{ post.body[:90] }}..
                                {% endif %}
                            </figcaption>
                        </figure>
                    </a>
                {% endfor %}
                <hr>
            </div>
        </div>
    {% endblock main %}

    {% block footer %}
        <div class="footer">
            <div class="container">
                <a class="btn btn-outline-dark" href="{{ url_for('blog.create_post') }}">Create Post</a>
            </div>
        </div>
    {% endblock footer %}

{% endblock content %}

someblog/blueprints/blog/templates/blog/index.html.j2
{% extends "bootstrap/base.html" %}

{% block navbar %}
    {% include 'base/nav.html.j2' %}
{% endblock %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <h1>Welcome to my posts</h1>
        </div>
    </div>
{% endblock %}

someblog/blueprints/blog/templates/blog/post.html
{% extends "bootstrap/base.html" %}

{% block navbar %}
    {% include 'base/nav.html' %}
{% endblock %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <div class="container">
        <h1>{{ post.title }}</h1>
        <div class="tags">
            {% for tag in tags %}
                <a href="tag/{{ tag.slug }}">
                    <span class="badge badge-{% if tag.id // 6 == 0 %}primary{% endif %}
                                             {% if tag.id // 6 == 1 %}success{% endif %}
                                             {% if tag.id // 6 == 2 %}info{% endif %}
                                             {% if tag.id // 6 == 3 %}warning{% endif %}
                                             {% if tag.id // 6 == 4 %}danger{% endif %}
                                             {% if tag.id // 6 == 5 %}dark{% endif %}
                    ">{{ tag.name }}</span>

                </a>
            {% endfor %}
        </div>
        <div class="main-content">
            {{ post.body }}
        </div>
    </div>
{% endblock %}

someblog/blueprints/blog/templates/blog/tag.html
{% extends "bootstrap/base.html" %}

{% block navbar %}
    {% include 'base/nav.html' %}
{% endblock %}

{% block title %}
    {{ tag.name }} posts
{% endblock %}

{% block content %}
    <div class="container">
        <h1>Posts with {{ tag.name }} tag</h1>
        {% for post in posts %}
            <div class="post">
                <a href="../{{ post.slug }}">{{ post.title }}</a>
            </div>
        {% endfor %}
    </div>
{% endblock %}